name: currency_converter
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  
  decimal: ^3.2.4
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  dio: ^5.0.0
  get_it: ^8.2.0
  connectivity_plus: ^6.1.5
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  talker_flutter: ^5.0.0
  talker_dio_logger: ^5.0.0
  talker_bloc_logger: ^5.0.0
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  build_runner: 


flutter:
  uses-material-design: true
  assets:
     - assets/flags/
